### ISSUE TITLE
How pass a hex string of signature for verifySingle

### ISSUE THREAD

**Issue by htiennv** [ARPA-Network/BLS-TSS-Network#47]
Hi team,

I'm reading BLS library contract ([BLS](https://github.com/ARPA-Network/BLS-TSS-Network/blob/main/contracts/src/libraries/BLS.sol)). And i want test a function:
 `verifySingle(uint256[2] memory signature, uint256[4] memory pubkey, uint256[2] memory message)`
 
 But i have a signature is a hex string format, looks like: `8f395739cc25f4d57fefb09afad7c1b704cc54cfb7dcabc433a758535b1000885c73e8728dd6369260aa0f99683670ff50195bdd47a7b904df10608a50e7f450`

The hex string format is produce by `drand` based on type of BLS algorithm. Example, it is a api of `drand` for get latest round:
[https://api.drand.sh/8990e7a9aaed2ffed73dbd7092123d6f289930540d7651336225dc172e51b2ce/public/latest](https://api.drand.sh/8990e7a9aaed2ffed73dbd7092123d6f289930540d7651336225dc172e51b2ce/public/latest)

Response in this time:
```
{
"round": 3358260,
"randomness": "68c5b8cf8c6f2d20e5128bdb453e01012290334f10fdfe371ed7a7fd6981ca9f",
"signature": "a1aef6d67ef2fce5bb61e2d3c2d40ff7672ac6caf59fd779b5bee83969e91612b280cf162aa2f1f03d4fc6bb3d3a6e320be37f89b3d7cba03a96a99b784534bef02691557a16484df0816735ea5bfff49915e3feaf5614c41953a4f9e05cab99",
"previous_signature": "8353cb629dd28f926bda024efdf8cf9d435a75433c41cb0ff639f01c5807425f6d21e36dec6c150603e7ac0fadb570d8033462f8079b915c14fc077a68d7777b395690e5244797e32830e0ace42461cd64607593ebf4d06c8c8b2c1cb398d517"
}
```
 
 How i can parse hex string to `uint256[2]`?

**Comment by kafeikui** [comment]
Hi @htiennv , there are multiple curves available for BLS scheme, for a pair of curves you can choose G1 or G2 scheme. For your case I think the signature is on G2 curve, so library like BN256G2.sol may help in general but you need to implement verification method manually. 

Besides, about the signature format, specifically the most significant bit for BN256, it's a custom field for developer to use. For other curves the position of that bit may be different. 

I Hope that helps to get you started.
