### ISSUE TITLE
Mocked smart contract code gets obsolete

### ISSUE THREAD

**Issue by neptune-v** [ARPA-Network/BLS-TSS-Network#5]
@kafeikui @wrinkledeth 

The prototype code relied on the mocked adapter, controller, and coordinator to run, however, the mocked smart contract code works differently than the actual smart contract integration, and because of these differences, the mocked smart contract code will slowly get obsolete as the development continues. 

Our options are:

1. Use Forge and the actual solidity implementation as a reference for the smart contract part, and completely remove the mocked code. And we can directly test with Forge + real smart contract. Since we will be integrating with EVM-based blockchain, to begin with anyway.

2. Constantly updating the mocked code to more realistically mock the smart contract so that we can test the node without the solidity environment, however, the test quality will degrade if the mocked code diverges from the smart contract implementation.

I suggest option 1 but open to different opinions.

**Comment by wrinkledeth** [comment]
I agree that option 1 makes more sense, especially in the long run. We probably need to wait until the contract is more developed, and we've tested the foundry integration before removing the mocked code.

**Comment by wrinkledeth** [comment]
*reopening issue (sorry, closed by accident)

**Comment by kafeikui** [comment]
Done by pr #21
